export const sagaActions = {
  FETCH_COURSES_SAGA_ACTION: "FETCH_COURSES_SAGA_ACTION",
  FETCH_POSTS_SAGA_ACTION: "FETCH_POSTS_SAGA_ACTION",
  DELETE_A_COURSE: "DELETE_A_COURSE",
  AUTHENTICATE_USER: "AUTHENTICATE_USER",
};
